version: 2.0

version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:
      - checkout
      - run: test.groovy